INSERT INTO coins (name, ticker)
VALUES 
    ('Bitcoin''BTC', GETDATE()),
    ('Ethereum', 'ETH', GETDATE()),
    ('Ripple', 'XRP', GETDATE()),
    ('Bitcoin Ca',   'BCH', GETDATE()),
    ('Cardano', 'ADA', GETDATE()),
    ('Litecoin', 'LTC', GETDATE()),
    ('NEO', 'NEO', GETDATE()),
    ('NEM', 'XEM', GETDATE()),
    ('Stellar', 'XLM', GETDATE()),
    ('IOTA', 'MIOTA', GETDATE()),
    ('EOS', 'EOS', GETDATE()),
    ('Dash', 'DASH', GETDATE())


    ('Monero', 'XMR', GETDATE(), GETDATE()),
    ('TRON', 'TRX', GETDATE(), GETDATE()),
    ('Bitcoin Go',   'BTG', GETDATE(), GETDATE()),
    ('Ethereum Class',   'ETC', GETDATE(), GETDATE()),
    ('Qtum', 'QTUM', GETDATE(), GETDATE()),
    ('ICON', 'ICX', GETDATE(), GETDATE()),
    ('Lisk', 'LSK', GETDATE(), GETDATE()),
    ('RaiBlocks', 'XRB', GETDATE(), GETDATE()),
    ('Ardor', 'ARDR', GETDATE(), GETDATE()),
    ('OmiseGO', 'OMG', GETDATE(), GETDATE()),
    ('Zcash', 'ZEC', GETDATE(), GETDATE()),
    ('Stratis', 'STRAT', GETDATE(), GETDATE()),
    ('Binance Co',   'BNB', GETDATE(), GETDATE()),
    ('BitConnect', 'BCC', GETDATE(), GETDATE()),
    ('Siacoin', 'SC', GETDATE(), GETDATE()),
    ('Bytecoin', 'BCN', GETDATE(), GETDATE()),
    ('Verge', 'XVG', GETDATE(), GETDATE()),
    ('Populous', 'PPT', GETDATE(), GETDATE()),
    ('VeChain', 'VEN', GETDATE(), GETDATE()),
    ('Tether', 'USDT', GETDATE(), GETDATE()),
    ('Status', 'SNT', GETDATE(), GETDATE()),
    ('Steem', 'STEEM', GETDATE(), GETDATE()),
    ('BitShares', 'BTS', GETDATE(), GETDATE()),
    ('KuCoin Shar',   'KCS', GETDATE(), GETDATE()),
    ('Dogecoin', 'DOGE', GETDATE(), GETDATE()),
    ('Waves', 'WAVES', GETDATE(), GETDATE()),
    ('Augur', 'REP', GETDATE(), GETDATE()),
    ('0x', 'ZRX', GETDATE(), GETDATE()),
    ('Gas', 'GAS', GETDATE(), GETDATE()),
    ('Dragonchain', 'DRGN', GETDATE(), GETDATE()),
    ('Veritaseum', 'VERI', GETDATE(), GETDATE()),
    ('Komodo', 'KMD', GETDATE(), GETDATE()),
    ('DigiByte', 'DGB', GETDATE(), GETDATE()),
    ('Electroneum', 'ETN', GETDATE(), GETDATE()),
    ('Golem', 'GNT', GETDATE(), GETDATE()),
    ('Ark', 'ARK', GETDATE(), GETDATE()),
    ('QASH', 'QASH', GETDATE(), GETDATE()),
    ('Hshare', 'HSR', GETDATE(), GETDATE()),
    ('SALT', 'SALT', GETDATE(), GETDATE()),
    ('SmartCash', 'SMART', GETDATE(), GETDATE()),
    ('Decred', 'DCR', GETDATE(), GETDATE()),
    ('Loopring', 'LRC', GETDATE(), GETDATE()),
    ('WAX', 'WAX', GETDATE(), GETDATE()),
    ('Dentacoin', 'DCN', GETDATE(), GETDATE()),
    ('Basic AttentioToken',   'BAT', GETDATE(), GETDATE()),
    ('PIVX', 'PIVX', GETDATE(), GETDATE()),
    ('ZClassic', 'ZCL', GETDATE(), GETDATE()),
    ('Walton', 'WTC', GETDATE(), GETDATE()),
    ('Kyber Netwo',   'KNC', GETDATE(), GETDATE()),
    ('Byteball Byt',   'GBYTE', GETDATE(), GETDATE()),
    ('FunFair', 'FUN', GETDATE(), GETDATE()),
    ('Factom', 'FCT', GETDATE(), GETDATE()),
    ('Aion', 'AION', GETDATE(), GETDATE()),
    ('Ethos', 'ETHOS', GETDATE(), GETDATE()),
    ('Bytom', 'BTM', GETDATE(), GETDATE()),
    ('MonaCoin', 'MONA', GETDATE(), GETDATE()),
    ('Experience Poin',   'XP', GETDATE(), GETDATE()),
    ('ReddCoin', 'RDD', GETDATE(), GETDATE()),
    ('Dent', 'DENT', GETDATE(), GETDATE()),
    ('GXShares', 'GXS', GETDATE(), GETDATE()),
    ('MaidSafeCoin', 'MAID', GETDATE(), GETDATE()),
    ('Syscoin', 'SYS', GETDATE(), GETDATE()),
    ('Substratum', 'SUB', GETDATE(), GETDATE()),
    ('RChain', 'RHOC', GETDATE(), GETDATE()),
    ('Power Ledg',   'POWR', GETDATE(), GETDATE()),
    ('Enigma', 'ENG', GETDATE(), GETDATE()),
    ('Aeternity', 'AE', GETDATE(), GETDATE()),
    ('Nxt', 'NXT', GETDATE(), GETDATE()),
    ('GameCredits', 'GAME', GETDATE(), GETDATE()),
    ('Request Netwo',   'REQ', GETDATE(), GETDATE()),
    ('Kin', 'KIN', GETDATE(), GETDATE()),
    ('MediBloc', 'MED', GETDATE(), GETDATE()),
    ('Nexus', 'NXS', GETDATE(), GETDATE()),
    ('DigixDAO', 'DGD', GETDATE(), GETDATE()),
    ('Particl', 'PART', GETDATE(), GETDATE()),
    ('Bancor', 'BNT', GETDATE(), GETDATE()),
    ('Nebulas', 'NAS', GETDATE(), GETDATE()),
    ('ZCoin', 'XZC', GETDATE(), GETDATE()),
    ('aelf', 'ELF', GETDATE(), GETDATE()),
    ('TenX', 'PAY', GETDATE(), GETDATE()),
    ('Iconomi', 'ICN', GETDATE(), GETDATE()),
    ('Neblio', 'NEBL', GETDATE(), GETDATE()),
    ('Civic', 'CVC', GETDATE(), GETDATE()),
    ('Gnosis', 'GNO', GETDATE(), GETDATE()),
    ('Cryptonex', 'CNX', GETDATE(), GETDATE()),
    ('DigitalNote', 'XDN', GETDATE(), GETDATE()),
    ('ChainLink', 'LINK', GETDATE(), GETDATE()),
    ('BitcoinDark', 'BTCD', GETDATE(), GETDATE())