// SQL DB INSERT COMMAND
INSERT INTO coins (name, ticker, createdAt)
VALUES 
    ('Bitcoin''BTC', '2018-01-12 12:27:38.749-08'),
    ('Ethereum', 'ETH', '2018-01-12 12:27:38.749-08'),
    ('Ripple', 'XRP', '2018-01-12 12:27:38.749-08'),
    ('Bitcoin Ca',   'BCH', '2018-01-12 12:27:38.749-08'),
    ('Cardano', 'ADA', '2018-01-12 12:27:38.749-08')
    ('Litecoin', 'LTC'),
    ('NEO', 'NEO'),
    ('NEM', 'XEM'),
    ('Stellar', 'XLM'),
    ('IOTA', 'MIOTA'),
    ('EOS', 'EOS'),
    ('Dash', 'DASH'),
    ('Monero', 'XMR'),
    ('TRON', 'TRX'),
    ('Bitcoin Go',   'BTG'),
    ('Ethereum Class',   'ETC'),
    ('Qtum', 'QTUM'),
    ('ICON', 'ICX'),
    ('Lisk', 'LSK'),
    ('RaiBlocks', 'XRB'),
    ('Ardor', 'ARDR'),
    ('OmiseGO', 'OMG'),
    ('Zcash', 'ZEC'),
    ('Stratis', 'STRAT'),
    ('Binance Co',   'BNB'),
    ('BitConnect', 'BCC'),
    ('Siacoin', 'SC'),
    ('Bytecoin', 'BCN'),
    ('Verge', 'XVG'),
    ('Populous', 'PPT'),
    ('VeChain', 'VEN'),
    ('Tether', 'USDT'),
    ('Status', 'SNT'),
    ('Steem', 'STEEM'),
    ('BitShares', 'BTS'),
    ('KuCoin Shar',   'KCS'),
    ('Dogecoin', 'DOGE'),
    ('Waves', 'WAVES'),
    ('Augur', 'REP'),
    ('0x', 'ZRX'),
    ('Gas', 'GAS'),
    ('Dragonchain', 'DRGN'),
    ('Veritaseum', 'VERI'),
    ('Komodo', 'KMD'),
    ('DigiByte', 'DGB'),
    ('Electroneum', 'ETN'),
    ('Golem', 'GNT'),
    ('Ark', 'ARK'),
    ('QASH', 'QASH'),
    ('Hshare', 'HSR'),
    ('SALT', 'SALT'),
    ('SmartCash', 'SMART'),
    ('Decred', 'DCR'),
    ('Loopring', 'LRC'),
    ('WAX', 'WAX'),
    ('Dentacoin', 'DCN'),
    ('Basic AttentioToken',   'BAT'),
    ('PIVX', 'PIVX'),
    ('ZClassic', 'ZCL'),
    ('Walton', 'WTC'),
    ('Kyber Netwo',   'KNC'),
    ('Byteball Byt',   'GBYTE'),
    ('FunFair', 'FUN'),
    ('Factom', 'FCT'),
    ('Aion', 'AION'),
    ('Ethos', 'ETHOS'),
    ('Bytom', 'BTM'),
    ('MonaCoin', 'MONA'),
    ('Experience Poin',   'XP'),
    ('ReddCoin', 'RDD'),
    ('Dent', 'DENT'),
    ('GXShares', 'GXS'),
    ('MaidSafeCoin', 'MAID'),
    ('Syscoin', 'SYS'),
    ('Substratum', 'SUB'),
    ('RChain', 'RHOC'),
    ('Power Ledg',   'POWR'),
    ('Enigma', 'ENG'),
    ('Aeternity', 'AE'),
    ('Nxt', 'NXT'),
    ('GameCredits', 'GAME'),
    ('Request Netwo',   'REQ'),
    ('Kin', 'KIN'),
    ('MediBloc', 'MED'),
    ('Nexus', 'NXS'),
    ('DigixDAO', 'DGD'),
    ('Particl', 'PART'),
    ('Bancor', 'BNT'),
    ('Nebulas', 'NAS'),
    ('ZCoin', 'XZC'),
    ('aelf', 'ELF'),
    ('TenX', 'PAY'),
    ('Iconomi', 'ICN'),
    ('Neblio', 'NEBL'),
    ('Civic', 'CVC'),
    ('Gnosis', 'GNO'),
    ('Cryptonex', 'CNX'),
    ('DigitalNote', 'XDN'),
    ('ChainLink', 'LINK'),
    ('BitcoinDark', 'BTCD');